name: BatchCast
options:
  bundleIdPrefix: com.shimondeitel.jewelrycastlog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  BatchCast:
    type: application
    platform: iOS
    sources:
      - path: BatchCast
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.jewelrycastlog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: BatchCast/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  BatchCastTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BatchCastTests
      - path: BatchCast.storekit
    dependencies:
      - target: BatchCast
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.jewelrycastlog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  BatchCastUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: BatchCastUITests
    dependencies:
      - target: BatchCast
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.jewelrycastlog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  BatchCast:
    build:
      targets:
        BatchCast: all
        BatchCastTests: [test]
        BatchCastUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: BatchCast.storekit
    test:
      config: Debug
      storeKitConfiguration: BatchCast.storekit
      targets:
        - BatchCastTests
        - BatchCastUITests
    archive:
      config: Release
